# Generated by Django 3.0.5 on 2020-12-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_replytoreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replytoreply',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
