# Generated by Django 3.0.8 on 2020-12-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
